### ISSUE TITLE
[DS5] Support regions

### ISSUE THREAD

**Issue by twardoch** [daltonmaag/file-format-discussion#10]
Variable fonts allow masters to act on regions, so each delta can have a min, peak and max location. But old DesignSpace only allows specifying peak. 

This makes building fonts with locally-active masters impossible when one uses tools like fontmake.

Also, with the image below, if I add a master like shown in (2), then its deltas bleed across the varspace as shown in (2), effectively polluting the varspace. Currently, one has to create a fake counter-master as shown in (3) but it's tedious and inefficient. We’d like the interpolation to work as shown in (4), without the fake counter-master. 

![05B2CE76-C197-401C-B3B1-9EF5BC00AA5D](https://user-images.githubusercontent.com/519108/135889268-1d8a69d1-e6c6-40a8-a465-fd4d43cd5310.jpeg)

DS5 should allow defining min and max of the master's location, not just peak.

**Comment by belluzj** [comment]
If I understand correctly, at the moment it's varLib's job to figure out the extent of each master's region, right? And what you'd like to do is be able to specify that yourself in the DS and have varLib/whichever use your regions?

Would you mind writing out the data that you would want to specify for your example above? (it doesn't have to be in XML, it's not about the syntax (yet), just about having some sample numbers to picture the problem better)

**Comment by twardoch** [comment]
Yes, will do.

**Comment by twardoch** [comment]
Yes, the »pollution« example is just one specific case. But in general, it's about situations like this image from https://docs.microsoft.com/en-us/typography/opentype/spec/otvaroverview :

![0F61114B-7CD7-4AF8-8C48-5A2DDDD83331](https://user-images.githubusercontent.com/519108/135899600-39103746-e1aa-4a2b-95c3-aae3028622d6.png)

This cannot currently be expressed with DS at all.

**Comment by simoncozens** [comment]
This is not a bad idea but you will have to work out how it interacts with higher order delta sets. varLib does not directly correlate a master with a delta set, and nor should it; a master may end up producing more than one delta set. We should be able to specify where a master starts and stops, but this will require a reworking of varLib.models to solve the interpolation system correctly.

**Comment by belluzj** [comment]
So, currently we have:

```yaml
sources:
  - path: base.ufo
    location:
      Weight: 400
      Width: 100
  - path: extreme.ufo
    location:
      Weight: 900
      Width: 150
```

And Adam you would want to have something like the following?

```yaml
sources:
  - path: base.ufo
    location:
      Weight: 400
      Width: 100
  - path: font.ufo
    location:
      Weight:
        min: 600
        peak: 900
        max: 900
      Width:
        min: 100
        peak: 150
        max: 200
```

I don't know however how varLib is supposed to use it. @twardoch if you could illustrate how you want to fix your example "pollution" problem, that would be great; both by outlining the information you'd give to varLib, and how you would expect varLib to interpret it.

In general, I think Simon is right that we'll need to work out what exactly varLib can do with this data in order to decide on what data to provide, how and where to write it in the designspace.
